# Site Settings
title: "Logboek"
description: "voor wie 't lezen wil"
baseurl: "/clean-blog"
url: "https://fprisse.github.io"
theme: null #original jekyll-theme-cayman
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /:slug.html

# Einde Introductietekst
excerpt_separator: <!--more-->

# Markdown processor
markdown: kramdown

# Exclude these from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
