# Site Settings
title: My Blog
description: A minimal blog powered by the Cayman Jekyll theme.
baseurl: "/clean-blog"
url: "https://fprisse.github.io"
theme: jekyll-theme-cayman
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
permalink: /:slug.html

# Markdown processor
markdown: kramdown

# Exclude these from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
